language: go

go:
  - 1.4
  - 1.5
  - tip

sudo: false

install: 
  - go get -t -d -v ./...
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls

script:
  - ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken nnbCGE2FA2EASedINlurUhZNRjFzwewQp