language: go

go:
  - 1.4
  - 1.5
  - tip

sudo: false

install: 
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress